<?php

namespace app\models;

use yii\base\Model;

class ResponseForm extends Model
{
    public function rules()
    {
        return []; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [];
    }

}